### PR TITLE
 ISSUE-9 Fix duplicate dependencies bug

### PR DESCRIPTION
**Pull request by jamie-meyer**
Duplicate dependencies are now deleted when there are multiple dependencies in a file and at least one of them needs to be updated.

#9

### CODE REVIEW

**Comment by lewismc** [comment]
@jamie-meyer please resolve merge conflict.

**Comment by lewismc** [comment]
@jamie-meyer I am going to hold off on #14 until this PR is merged... it will just introduce even more merge conflict and make your life harder if I merge that now. Please update when you can. Thank you

**Comment by jamie-meyer** [comment]
@lewismc Merged. Python check is failing due to XML tree security issue that, to my knowledge, cannot be resolved without significant errors to fireant's pull request changes (all the comments in the file would be deleted).

**Comment by lewismc** [comment]
Hi @jamie-meyer see the changes I made to address the security vulnerabilities identified by deepsource.
I need you to verify that XML comments are retained... we can do that via a unit test so please create an issue and work on that. Thanks. Good work.

**Pull request merged**
